version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: workshops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    container_name: node-backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres_password
      DB_NAME: workshops_db
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9091:9000"
    networks:
      - app-network

volumes:
  postgres_data:
  portainer_data:

networks:
  app-network: